/**
 * Seed commentary — Batch 2: Ecclesiastes, Hosea, Daniel
 */
import Database from "better-sqlite3";
import path from "path";

const dbPath = path.resolve(import.meta.dirname, "..", "data", "armorlight.db");
const db = new Database(dbPath);

interface CommentaryGroup { verseStart: number; verseEnd: number; text: string; }
interface BookCommentary { slug: string; chapters: Record<number, CommentaryGroup[]>; }

function seedBook(book: BookCommentary) {
    const bookRow = db.prepare(`SELECT id, name FROM books WHERE slug = ?`).get(book.slug) as any;
    if (!bookRow) { console.log(`  Not found: ${book.slug}`); return; }
    let inserted = 0;
    for (const [chStr, groups] of Object.entries(book.chapters)) {
        const ch = Number(chStr);
        for (const group of groups) {
            const verses = db.prepare(`SELECT id FROM verses WHERE book_id = ? AND chapter = ? AND verse BETWEEN ? AND ? ORDER BY verse`)
                .all(bookRow.id, ch, group.verseStart, group.verseEnd) as { id: number }[];
            for (const v of verses) {
                const exists = db.prepare(`SELECT 1 FROM commentaries WHERE verse_id = ?`).get(v.id);
                if (exists) continue;
                db.prepare(`INSERT INTO commentaries (verse_id, author, text, source) VALUES (?, 'Matthew Henry', ?, 'Concise Commentary')`)
                    .run(v.id, group.text);
                inserted++;
            }
        }
    }
    console.log(`  ${bookRow.name}: ${inserted} entries`);
}

// ═══════════════════════════════════════════════════════════════════
// ECCLESIASTES (222 verses, 12 chapters)
// ═══════════════════════════════════════════════════════════════════
seedBook({
    slug: "ecclesiastes", chapters: {
        1: [
            { verseStart: 1, verseEnd: 3, text: "Verses 1–3 The words of the Preacher, the son of David, king in Jerusalem. Solomon, having tasted all earthly pleasures, found them vanity — emptiness and vexation. 'Vanity of vanities, all is vanity.' What profit has a man from all his labor under the sun? This is the great question that the book explores: what is the meaning and purpose of human toil without God?" },
            { verseStart: 4, verseEnd: 11, text: "Verses 4–11 One generation passes away and another comes, but the earth remains forever. The sun rises and sets, the wind blows in circuits, all rivers run to the sea yet the sea is not full. All things are full of labour, the eye is not satisfied with seeing, nor the ear with hearing. There is nothing new under the sun. The endless cycles of nature illustrate the weariness of a life without eternal purpose." },
            { verseStart: 12, verseEnd: 18, text: "Verses 12–18 The Preacher set his heart to seek wisdom concerning all that is done under heaven. He saw all the works done under the sun and found them vanity and vexation of spirit. What is crooked cannot be made straight. In much wisdom is much grief; he that increases knowledge increases sorrow. Human wisdom alone, without the fear of God, leads to despair rather than satisfaction." },
        ],
        2: [
            { verseStart: 1, verseEnd: 11, text: "Verses 1–11 Solomon tested his heart with pleasure, mirth, wine, and great works — houses, vineyards, gardens, orchards, pools, servants, herds. He gathered silver and gold, singers, and every delight. He was greater than all before him in Jerusalem. Yet when he looked at all his works, behold, all was vanity and vexation of spirit. There was no profit under the sun. Even the greatest achievements apart from God are ultimately meaningless." },
            { verseStart: 12, verseEnd: 17, text: "Verses 12–17 The Preacher turned to consider wisdom, madness, and folly. Wisdom excels folly as light excels darkness: the wise man's eyes are in his head, but the fool walks in darkness. Yet one event happens to them all — death. Solomon hated life, for all was vanity, because the wise and the fool share the same fate under the sun." },
            { verseStart: 18, verseEnd: 26, text: "Verses 18–26 He hated all his labor, for he must leave it to the one who comes after him — and who knows whether he will be wise or a fool? Therefore Solomon despaired. Yet he concludes that there is nothing better than that a man should eat, drink, and find enjoyment in his work, for this too comes from the hand of God. To the one who pleases him, God gives wisdom, knowledge, and joy." },
        ],
        3: [
            { verseStart: 1, verseEnd: 8, text: "Verses 1–8 To everything there is a season, and a time for every purpose under heaven: a time to be born and a time to die; a time to plant and a time to pluck up; a time to kill and a time to heal; a time to weep and a time to laugh; a time to mourn and a time to dance; a time to keep silence and a time to speak; a time for war and a time for peace. God has appointed every season. Wisdom lies in discerning the right time for each action." },
            { verseStart: 9, verseEnd: 15, text: "Verses 9–15 What profit has the worker in his toil? God has made everything beautiful in its time. He has also set eternity in the hearts of men — yet they cannot fathom what God has done from beginning to end. There is nothing better than for a man to rejoice and do good. Whatever God does, it shall be forever; nothing can be added to it, nothing taken from it. God does it so that men should fear before him." },
            { verseStart: 16, verseEnd: 22, text: "Verses 16–22 In the place of judgment there was wickedness. The Preacher reflects that God will judge the righteous and the wicked. Man's fate and the beast's fate are alike — both die, both return to dust. Who knows whether the spirit of man goes upward? Therefore, there is nothing better than for a man to rejoice in his works, for that is his portion. These honest reflections wrestle with mortality and trust in God's ultimate justice." },
        ],
        4: [
            { verseStart: 1, verseEnd: 6, text: "Verses 1–6 The Preacher saw the oppressions under the sun — the tears of the oppressed with no comforter. He considered that the dead are better off than the living, and those yet unborn better than both. Better is a handful of quietness than two hands full of toil and striving after wind. The competitive spirit that drives men to outdo each other is itself vanity." },
            { verseStart: 7, verseEnd: 12, text: "Verses 7–12 Again, vanity under the sun: a solitary man with no companion, no son or brother, yet never satisfied with his riches. Two are better than one — they have a good reward for their labor. If one falls, the other lifts him up. A threefold cord is not quickly broken. Companionship and community are God's gifts against isolation." },
            { verseStart: 13, verseEnd: 16, text: "Verses 13–16 Better is a poor and wise youth than an old and foolish king who will no longer take advice. Yet even the successor is soon forgotten. This is also vanity and vexation of spirit. Popularity and political power are fleeting — each generation forgets the last." },
        ],
        5: [
            { verseStart: 1, verseEnd: 7, text: "Verses 1–7 Guard your steps when you go to the house of God. Draw near to listen rather than to offer the sacrifice of fools. Be not rash with your mouth; let your words be few, for God is in heaven and you are on earth. When you make a vow, pay it. Do not let your mouth cause your body to sin. In a multitude of dreams and words there is vanity — but fear God." },
            { verseStart: 8, verseEnd: 17, text: "Verses 8–17 If you see oppression of the poor, do not be amazed, for there are higher officials watching over them. He who loves money will not be satisfied with money. When goods increase, those who consume them increase. The sleep of a laboring man is sweet, but the abundance of the rich will not let him sleep. Riches kept for their owner to his hurt — a grievous evil under the sun." },
            { verseStart: 18, verseEnd: 20, text: "Verses 18–20 What the Preacher finds good: to eat, drink, and find enjoyment in all the toil of one's life — this is God's gift. When God gives wealth and the power to enjoy it, and to accept his lot and rejoice in his toil — this is the gift of God. Such a man will not much remember the days of his life because God keeps him occupied with joy in his heart." },
        ],
        6: [
            { verseStart: 1, verseEnd: 6, text: "Verses 1–6 There is an evil: a man whom God gives wealth, possessions, and honor, but God does not give him the power to enjoy them. A stranger enjoys them instead. Even if a man fathers a hundred children and lives many years, if his soul is not satisfied with good things, the Preacher says a stillborn child is better off. Without the ability to enjoy God's gifts, length of days means nothing." },
            { verseStart: 7, verseEnd: 12, text: "Verses 7–12 All the toil of man is for his mouth, yet his appetite is never satisfied. What advantage has the wise over the fool? Better is the sight of the eyes than the wandering of desire. Whatever has been named was known long ago. Man cannot dispute with one stronger than he. The more words, the more vanity. Who knows what is good for man during the few days of his vain life? Who can tell him what will be after him under the sun?" },
        ],
        7: [
            { verseStart: 1, verseEnd: 6, text: "Verses 1–6 A good name is better than precious ointment, and the day of death than the day of birth. Better to go to the house of mourning than the house of feasting, for this is the end of every man. Sorrow is better than laughter, for by sadness the heart is made glad. The heart of the wise is in the house of mourning, but the heart of fools is in the house of mirth. Better to hear the rebuke of the wise than the song of fools." },
            { verseStart: 7, verseEnd: 14, text: "Verses 7–14 Oppression makes the wise man foolish. Better is the end of a thing than its beginning. The patient in spirit is better than the proud. Do not say 'Why were the former days better than these?' for that is not wisdom. Wisdom is good with an inheritance. Wisdom preserves the life of its possessor. Consider the work of God: who can make straight what he has made crooked? In prosperity, rejoice; in adversity, consider — God has made both." },
            { verseStart: 15, verseEnd: 22, text: "Verses 15–22 The Preacher has seen both: a righteous man perishing in his righteousness, and a wicked man prolonging his life. Be not overly righteous, nor overly wicked. Fear God and hold to both. Wisdom strengthens the wise more than ten rulers. There is not a righteous man on earth who does good and never sins. Do not take to heart everything people say, for you yourself know you have cursed others. The balanced life acknowledges human frailty while fearing God." },
            { verseStart: 23, verseEnd: 29, text: "Verses 23–29 All this the Preacher tested by wisdom. He sought to find the scheme of things but found it far off and deep. He turned to know wickedness and folly. The woman whose heart is snares and nets is more bitter than death. One man among a thousand he found, but a woman among all these he has not found. What he has found: God made man upright, but they have sought out many schemes." },
        ],
        8: [
            { verseStart: 1, verseEnd: 8, text: "Verses 1–8 Who is like the wise man? Wisdom makes a man's face shine. Keep the king's command because of your oath to God. Do not be hasty to leave his presence. The word of a king is supreme; who can say, 'What are you doing?' He who keeps a command will know no harm. The wise heart knows the proper time and procedure. There is a time and way for everything. No man has power over the wind or over the day of death." },
            { verseStart: 9, verseEnd: 13, text: "Verses 9–13 The Preacher observed men exercising authority over others to their hurt. The wicked are buried and praised while the righteous are forgotten. Because sentence against evil is not executed speedily, the hearts of men are set to do evil. Yet surely it will be well with those who fear God, and it will not be well with the wicked. His days are like a shadow, because he does not fear before God." },
            { verseStart: 14, verseEnd: 17, text: "Verses 14–17 There is a vanity on earth: righteous men who receive what the wicked deserve, and wicked men who receive what the righteous deserve. The Preacher commends joy, for man has nothing better under the sun than to eat, drink, and be joyful. Though man cannot find out the work that God does, even if a wise man claims to know it, he cannot. The mysteries of God's providence are ultimately beyond human understanding." },
        ],
        9: [
            { verseStart: 1, verseEnd: 6, text: "Verses 1–6 The righteous and wise are in the hand of God, yet man does not know whether love or hate awaits him. One fate comes to all — righteous and wicked, clean and unclean, the one who sacrifices and the one who does not. The hearts of men are full of evil, and madness is in their hearts while they live. A living dog is better than a dead lion, for the living know they will die, but the dead know nothing." },
            { verseStart: 7, verseEnd: 12, text: "Verses 7–12 Go, eat your bread with joy and drink your wine with a merry heart, for God has already approved what you do. Enjoy life with the wife you love. Whatever your hand finds to do, do it with all your might, for there is no work or thought or knowledge in Sheol. The race is not to the swift, nor the battle to the strong. Time and chance happen to all. Man does not know his time — like fish caught in a net, so are men snared in an evil time." },
            { verseStart: 13, verseEnd: 18, text: "Verses 13–18 The Preacher observed great wisdom: a small city besieged by a great king. A poor wise man delivered it, yet no one remembered him. Wisdom is better than strength, yet the poor man's wisdom is despised. Quiet words of the wise are better than the shouting of a ruler among fools. Wisdom is better than weapons of war, but one sinner destroys much good." },
        ],
        10: [
            { verseStart: 1, verseEnd: 7, text: "Verses 1–7 Dead flies make the perfumer's ointment stink; so a little folly outweighs wisdom and honour. A wise man's heart inclines to the right, a fool's to the left. Even when the fool walks, his sense fails him. If the ruler's temper rises against you, do not leave your place; calmness will lay great offences to rest. There is an evil: folly set in great dignity while the rich sit in low places. The Preacher has seen servants on horses while princes walk on foot." },
            { verseStart: 8, verseEnd: 15, text: "Verses 8–15 He who digs a pit may fall into it. He who quarries stones may be hurt by them. If the iron is blunt, one must use more strength; wisdom finds the advantage. If a snake bites before it is charmed, there is no advantage to the charmer. A wise man's words win him favour, but a fool's lips swallow him up. The beginning of his words is foolishness and the end is wicked madness. A fool multiplies words, yet no man knows what will be." },
            { verseStart: 16, verseEnd: 20, text: "Verses 16–20 Woe to you, O land, when your king is a child, and your princes feast in the morning! Blessed are you when your king is of noble birth and your princes eat at the proper time, for strength and not for drunkenness. Through sloth the roof sinks in, and through idleness the house leaks. Bread is made for laughter, wine gladdens life, and money answers everything. Do not curse the king even in your thoughts, for a bird of the air may carry your voice." },
        ],
        11: [
            { verseStart: 1, verseEnd: 6, text: "Verses 1–6 Cast your bread upon the waters, for you will find it after many days. Give a portion to seven, or even to eight, for you do not know what disaster may happen on earth. If clouds are full of rain, they empty themselves on the earth. He who observes the wind will not sow, and he who regards the clouds will not reap. You do not know the way of the spirit or how the bones grow in the womb. Sow your seed in the morning and do not withhold your hand in the evening, for you do not know which will prosper." },
            { verseStart: 7, verseEnd: 10, text: "Verses 7–10 Light is sweet, and it is pleasant for the eyes to see the sun. If a man lives many years, let him rejoice in them all, but remember the days of darkness will be many. Rejoice, O young man, in your youth! Let your heart cheer you. Walk in the ways of your heart and the sight of your eyes — but know that for all these things God will bring you into judgment. Remove sorrow from your heart, for youth and the dawn of life are vanity." },
        ],
        12: [
            { verseStart: 1, verseEnd: 7, text: "Verses 1–7 Remember your Creator in the days of your youth, before the evil days come and the years draw near when you say, 'I have no pleasure in them.' Before the sun and light and moon and stars grow dark and the clouds return after the rain; before the grinders cease because they are few, and those looking through windows grow dim; before the almond tree blossoms, the grasshopper becomes a burden, and desire fails — for man goes to his eternal home and mourners go about the streets. Remember him before the silver cord is snapped, the golden bowl broken, the pitcher shattered at the fountain, the wheel broken at the cistern — and the dust returns to earth, and the spirit returns to God who gave it." },
            { verseStart: 8, verseEnd: 14, text: "Verses 8–14 'Vanity of vanities,' says the Preacher, 'all is vanity.' The Preacher taught the people knowledge, weighing and studying and arranging many proverbs. He sought to find words of delight, and uprightly he wrote words of truth. The words of the wise are like goads, firmly fixed nails. Of making many books there is no end, and much study is a weariness of the flesh. The end of the matter: fear God and keep his commandments, for this is the whole duty of man. For God will bring every deed into judgment, including every hidden thing, whether good or evil. This is the book's great conclusion: all of life finds its meaning in the fear of God." },
        ],
    }
});

// ═══════════════════════════════════════════════════════════════════
// HOSEA (197 verses, 14 chapters)
// ═══════════════════════════════════════════════════════════════════
seedBook({
    slug: "hosea", chapters: {
        1: [
            { verseStart: 1, verseEnd: 5, text: "Verses 1–5 The Lord commands Hosea to take a wife of harlotry and children of harlotry, for the land commits great harlotry by forsaking the Lord. Hosea takes Gomer, and she bears him Jezreel — for God will avenge the blood of Jezreel on the house of Jehu and break the bow of Israel. This shocking command illustrates God's relationship with unfaithful Israel." },
            { verseStart: 6, verseEnd: 11, text: "Verses 6–11 Gomer bears a daughter called Lo-Ruhamah ('No Mercy'), for God will no longer have mercy on Israel. Then a son, Lo-Ammi ('Not My People'), for Israel is no longer God's people. Yet the number of Israel shall be as the sand of the sea, and where it was said 'Not My People,' they shall be called 'Children of the Living God.' Judah and Israel shall be gathered together. The sternest judgment carries a seed of ultimate restoration." },
        ],
        2: [
            { verseStart: 1, verseEnd: 8, text: "Verses 1–8 The Lord pleads with Israel as with an unfaithful wife. She has chased her lovers — the Baals — thinking they gave her bread, water, wool, and flax. But it was the Lord who gave them. Therefore God will hedge her way with thorns and build a wall so she cannot find her paths. She will follow her lovers but not overtake them, and say, 'I will go and return to my first husband.'" },
            { verseStart: 9, verseEnd: 13, text: "Verses 9–13 God will take back his grain, wine, wool, and flax. He will uncover her lewdness. He will end her feasts, new moons, sabbaths, and appointed assemblies. He will destroy her vines and fig trees which she said were her reward from her lovers. He will punish her for the days of the Baals when she burned incense to them and forgot the Lord." },
            { verseStart: 14, verseEnd: 23, text: "Verses 14–23 Therefore God will allure her, bring her into the wilderness, and speak tenderly to her. She will call him 'My Husband' and no more 'My Baal.' In that day God will make a covenant with the beasts, bow and sword will be abolished, and Israel will lie down in safety. 'I will betroth you to me forever — in righteousness, justice, steadfast love, and mercy. You shall know the Lord.' God will answer the heavens, they will answer the earth, and he will sow Israel in the land and have mercy." },
        ],
        3: [
            { verseStart: 1, verseEnd: 5, text: "Verses 1–5 The Lord says: 'Go again, love a woman who is loved by another man and is an adulteress, even as the Lord loves the children of Israel.' Hosea buys her for fifteen pieces of silver and grain. She must remain faithful. Israel shall dwell many days without king or prince, without sacrifice or sacred pillar. Afterward they shall return and seek the Lord their God and David their king. They shall come in fear to the Lord and his goodness in the latter days." },
        ],
        4: [
            { verseStart: 1, verseEnd: 10, text: "Verses 1–10 The Lord has a controversy with the inhabitants: there is no faithfulness, no steadfast love, no knowledge of God. Swearing, lying, killing, stealing, adultery — bloodshed follows bloodshed. The land mourns. My people are destroyed for lack of knowledge. Because you have rejected knowledge, I reject you from being a priest. The more they increased, the more they sinned. They feed on the sin of my people." },
            { verseStart: 11, verseEnd: 19, text: "Verses 11–19 Wine and new wine take away understanding. My people ask counsel of wood, and their staff declares to them. A spirit of harlotry has led them astray. They sacrifice on mountaintops and burn incense on hills. Their daughters commit harlotry, but God will not punish the daughters alone — the men themselves go apart with harlots. Ephraim is joined to idols; let him alone. Israel's conduct is deeply corrupt." },
        ],
        5: [
            { verseStart: 1, verseEnd: 7, text: "Verses 1–7 Hear this, O priests! Give heed, O house of Israel! The judgment is for you. You have been a snare at Mizpah and a net spread on Tabor. Their deeds will not permit them to return to God, for a spirit of harlotry is within them. Israel's pride testifies against him. They have dealt faithlessly with the Lord, for they have borne alien children." },
            { verseStart: 8, verseEnd: 15, text: "Verses 8–15 Blow the trumpet in Gibeah! Sound the alarm! Ephraim shall become a desolation. I will be like a moth to Ephraim, like dry rot to Judah. When Ephraim saw his sickness, he went to Assyria — but that king could not cure him. I will be like a lion to Ephraim, like a young lion to Judah. I will tear and go away. I will return to my place until they acknowledge their guilt and seek my face. In their distress they will earnestly seek me." },
        ],
        6: [
            { verseStart: 1, verseEnd: 6, text: "Verses 1–6 'Come, let us return to the Lord; for he has torn us, that he may heal us. After two days he will revive us; on the third day he will raise us up, that we may live before him.' Let us press on to know the Lord. But their loyalty is like a morning cloud, like dew that goes early away. God desires steadfast love, not sacrifice — the knowledge of God rather than burnt offerings." },
            { verseStart: 7, verseEnd: 11, text: "Verses 7–11 Like Adam, they have transgressed the covenant. Gilead is a city of evildoers, tracked with blood. Priests murder on the way to Shechem; they commit villainy. In the house of Israel a horrible thing is seen — harlotry in Ephraim, Israel is defiled. For you also, O Judah, a harvest is appointed when I restore the fortunes of my people. Even in denouncing sin, God anticipates restoration." },
        ],
        7: [
            { verseStart: 1, verseEnd: 7, text: "Verses 1–7 When God would heal Israel, the iniquity of Ephraim is revealed. They do not consider that God remembers all their evil. They make the king glad with wickedness. They are all adulterers, like a heated oven. On the day of their king, the princes are inflamed with wine. Their hearts are like an oven that smolders all night. None of them calls upon God." },
            { verseStart: 8, verseEnd: 16, text: "Verses 8–16 Ephraim mixes himself with the peoples; he is a cake not turned. Strangers devour his strength and he does not know it. Gray hairs are sprinkled upon him and he does not know it. Israel's pride testifies against them, yet they do not return to the Lord. Ephraim is like a silly dove, calling to Egypt, going to Assyria. They rebel against God, they speak lies against him. They do not cry to God from the heart but wail upon their beds. They return, but not upward. They are like a treacherous bow." },
        ],
        8: [
            { verseStart: 1, verseEnd: 7, text: "Verses 1–7 Blow the trumpet! An eagle is over the house of the Lord, because they have transgressed the covenant. Israel cries, 'My God, we know you!' But Israel has rejected what is good. They made kings without God's approval, princes without his acknowledgment. With silver and gold they made idols — to their own destruction. The calf of Samaria shall be broken to pieces. They sow the wind and reap the whirlwind." },
            { verseStart: 8, verseEnd: 14, text: "Verses 8–14 Israel is swallowed up, now among the nations like a useless vessel. They have gone up to Assyria like a wild donkey alone. Though they hire allies among the nations, God will gather them. Ephraim has multiplied altars for sinning. Though I write my law in ten thousand precepts, they count them as foreign. They sacrifice flesh and eat it, but the Lord does not accept them. Israel has forgotten his Maker and built palaces; Judah has multiplied fortified cities; but God will send fire upon their cities." },
        ],
        9: [
            { verseStart: 1, verseEnd: 9, text: "Verses 1–9 Rejoice not, O Israel! You have loved a prostitute's wages on every threshing floor. Threshing floor and winepress shall not feed them. They shall not remain in the Lord's land. Ephraim shall return to Egypt and eat unclean food in Assyria. What will you do on the day of the appointed festival? The days of punishment have come. The prophet is a fool, the man of the spirit is mad — because of great sin, great hostility. Ephraim was a watchman with God, yet a fowler's snare is on all his paths." },
            { verseStart: 10, verseEnd: 17, text: "Verses 10–17 Like grapes in the wilderness, God found Israel. Their fathers came to Baal-peor and consecrated themselves to that shameful thing. Ephraim's glory shall fly away — no birth, no pregnancy, no conception. Though they bring up children, God will bereave them. Give them, O Lord — what will you give? Give them a miscarrying womb and dry breasts. Because of their wickedness, God will drive them out of his house. My God will reject them because they did not listen. They shall be wanderers among the nations." },
        ],
        10: [
            { verseStart: 1, verseEnd: 8, text: "Verses 1–8 Israel is a luxuriant vine that yields its fruit. The more fruit he bore, the more altars he built. Their heart is false; now they must bear their guilt. They speak empty words, make covenants with lies. Because they have no king — for they did not fear the Lord — judgment springs up like poisonous weeds. The inhabitants of Samaria tremble for the calf of Beth-aven. Its glory has departed. The high places of wickedness shall be destroyed; thorn and thistle shall grow on their altars." },
            { verseStart: 9, verseEnd: 15, text: "Verses 9–15 Since the days of Gibeah, you have sinned, O Israel. Sow for yourselves righteousness, reap in mercy; break up your fallow ground, for it is time to seek the Lord, till he comes and rains righteousness upon you. But you have plowed wickedness, reaped iniquity, eaten the fruit of lies. Because you trusted in your own way, in the multitude of your warriors, tumult shall arise among your people. The king of Israel shall be utterly cut off in the storm of judgment." },
        ],
        11: [
            { verseStart: 1, verseEnd: 7, text: "Verses 1–7 When Israel was a child, I loved him, and out of Egypt I called my son. But the more they were called, the more they went away. They sacrificed to the Baals. Yet it was I who taught Ephraim to walk, taking them up by their arms. I led them with cords of kindness, with bands of love. I bent down to them and fed them. They shall return to Egypt; Assyria shall be their king, because they have refused to return to me." },
            { verseStart: 8, verseEnd: 12, text: "Verses 8–12 How can I give you up, O Ephraim? How can I hand you over, O Israel? My heart recoils within me; my compassion grows warm and tender. I will not execute my burning anger; I will not again destroy Ephraim, for I am God and not a man — the Holy One in your midst. I will not come in wrath. They shall follow the Lord; he will roar like a lion, and his children shall come trembling from the west. God's mercy triumphs over his judgment — the strongest declaration of divine compassion in the book." },
        ],
        12: [
            { verseStart: 1, verseEnd: 6, text: "Verses 1–6 Ephraim feeds on wind and pursues the east wind all day. They multiply lies and violence. They make a covenant with Assyria, and oil is carried to Egypt. The Lord has a controversy also with Judah. Jacob in the womb took his brother by the heel; in his strength he strove with God. He strove with the angel and prevailed; he wept and sought his favour. He found him at Bethel. Turn to your God; keep mercy and justice, and wait continually on your God." },
            { verseStart: 7, verseEnd: 14, text: "Verses 7–14 A merchant with dishonest scales in his hand — he loves to oppress. Ephraim says, 'I have become rich.' But his riches shall not save him from his sin. I am the Lord your God from the land of Egypt; I will make you dwell in tents again. I spoke to the prophets, gave many visions, and spoke in parables. Ephraim has provoked God bitterly, and his Lord will leave his bloodguilt upon him. By a prophet the Lord brought Israel out of Egypt, and by a prophet he was guarded." },
        ],
        13: [
            { verseStart: 1, verseEnd: 8, text: "Verses 1–8 When Ephraim spoke, there was trembling; he was exalted in Israel. But through Baal he incurred guilt and died. Now they sin more and more, making idols of silver. They shall be like the morning mist that passes away. Yet I am the Lord your God from the land of Egypt; you know no God but me, and besides me there is no saviour. I knew you in the wilderness. When they were satisfied, their heart was lifted up; therefore they forgot me. I am like a lion, like a leopard, like a bear robbed of her cubs." },
            { verseStart: 9, verseEnd: 16, text: "Verses 9–16 He destroys you, O Israel, for you are against me, against your helper. Where now is your king? Give me a king and princes! God gave a king in his anger and took him away in his wrath. The iniquity of Ephraim is stored up. The pangs of childbirth come upon him. Shall I ransom them from death? Shall I redeem them from Sheol? O Death, where are your plagues? O Sheol, where is your sting? Compassion is hid from my eyes. Though Ephraim flourishes among reeds, the east wind shall come — the breath of the Lord." },
        ],
        14: [
            { verseStart: 1, verseEnd: 3, text: "Verses 1–3 Return, O Israel, to the Lord your God, for you have stumbled because of your iniquity. Take words with you and return to the Lord. Say to him: 'Take away all iniquity; accept what is good, and we will offer the fruit of our lips. Assyria shall not save us; we will not say again to the work of our hands, You are our gods.' In God the orphan finds mercy. True repentance confesses specific sins, renounces false refuges, and trusts in God's mercy alone." },
            { verseStart: 4, verseEnd: 9, text: "Verses 4–9 'I will heal their apostasy; I will love them freely, for my anger has turned from them.' God will be like the dew to Israel; he shall blossom like the lily and take root like the trees of Lebanon. His shoots shall spread out; his beauty shall be like the olive tree. Those who dwell in his shadow shall return and flourish. 'O Ephraim, what have I to do with idols? It is I who answer and look after you.' Whoever is wise, let him understand these things; the ways of the Lord are right, and the upright walk in them, but transgressors stumble in them. The book ends with the magnificent promise of healing and the beauty of restored relationship." },
        ],
    }
});

// ═══════════════════════════════════════════════════════════════════
// DANIEL (357 verses, 12 chapters)
// ═══════════════════════════════════════════════════════════════════
seedBook({
    slug: "daniel", chapters: {
        1: [
            { verseStart: 1, verseEnd: 7, text: "Verses 1–7 Nebuchadnezzar king of Babylon besieged Jerusalem and carried away the vessels of God's house. The king commanded to bring certain young men of Israel — without blemish, skillful in wisdom — to serve in his court. Among them were Daniel, Hananiah, Mishael, and Azariah, whose names were changed to Babylonian names. Even in captivity, God prepared his servants for great purposes." },
            { verseStart: 8, verseEnd: 16, text: "Verses 8–16 Daniel purposed in his heart not to defile himself with the king's food and wine. He asked the chief of the eunuchs for permission to eat vegetables and drink water. God gave Daniel favour. After ten days, Daniel and his friends appeared fairer and fatter than those who ate the king's food. The steward continued to give them vegetables. Faithful obedience to God, even in small matters, brings blessing and favor." },
            { verseStart: 17, verseEnd: 21, text: "Verses 17–21 God gave these four young men learning, skill, and wisdom. Daniel had understanding in all visions and dreams. When brought before Nebuchadnezzar, they were found ten times better than all the magicians and astrologers. Daniel continued until the first year of King Cyrus. God rewards faithfulness with extraordinary gifts and endurance." },
        ],
        2: [
            { verseStart: 1, verseEnd: 13, text: "Verses 1–13 Nebuchadnezzar dreamed dreams and his spirit was troubled. He demanded his wise men tell the dream and its interpretation — on pain of death. They protested: no king has ever asked such a thing. The decree went out to destroy all the wise men. Daniel was sought to be killed with them. The impossibility of men became the opportunity of God." },
            { verseStart: 14, verseEnd: 23, text: "Verses 14–23 Daniel sought time from the king, then went to his house and his companions joined him in prayer. The mystery was revealed to Daniel in a night vision. He blessed the God of heaven: 'He changes times and seasons; he removes and sets up kings; he gives wisdom to the wise. He reveals deep and hidden things; he knows what is in darkness, and the light dwells with him.' God answers the prayers of his people in their extremity." },
            { verseStart: 24, verseEnd: 35, text: "Verses 24–35 Daniel tells the king his dream: a great and bright image with a head of gold, chest and arms of silver, belly and thighs of bronze, legs of iron, and feet of iron mixed with clay. A stone cut without hands struck the image on its feet and broke the whole statue to pieces, and the stone became a great mountain filling the whole earth." },
            { verseStart: 36, verseEnd: 45, text: "Verses 36–45 Daniel interprets: the head of gold is Nebuchadnezzar's kingdom of Babylon. After him shall arise kingdoms of silver (Medo-Persia), bronze (Greece), and iron (Rome). The feet of iron and clay represent a divided kingdom. In the days of these kings, the God of heaven will set up a kingdom that shall never be destroyed — the stone that becomes a mountain. This kingdom is Christ's eternal reign, which shatters all earthly powers." },
            { verseStart: 46, verseEnd: 49, text: "Verses 46–49 Nebuchadnezzar falls on his face and pays homage to Daniel, confessing that Daniel's God is the God of gods. He promotes Daniel over the whole province of Babylon, and at Daniel's request, his three friends receive positions also. When God reveals truth through his servants, even pagan rulers acknowledge his supremacy." },
        ],
        3: [
            { verseStart: 1, verseEnd: 7, text: "Verses 1–7 Nebuchadnezzar makes a golden image ninety feet tall and sets it up on the plain of Dura. He commands all officials to bow down and worship the image when they hear the music. Whoever does not fall down and worship shall be cast into a burning fiery furnace. The pressure to conform is immense, yet God always preserves a remnant who refuse to bow." },
            { verseStart: 8, verseEnd: 18, text: "Verses 8–18 Certain Chaldeans accuse Shadrach, Meshach, and Abednego of refusing to worship the golden image. The king in fury summons them and offers a second chance. Their answer is heroic: 'Our God whom we serve is able to deliver us from the burning fiery furnace. But even if he does not, let it be known to you, O king, that we will not serve your gods or worship the golden image.' This is one of the greatest declarations of faith in all of Scripture." },
            { verseStart: 19, verseEnd: 27, text: "Verses 19–27 The furnace is heated seven times hotter. The three are bound and cast in — the heat kills the soldiers who throw them. But Nebuchadnezzar sees four men walking in the fire, unbound and unharmed, and the fourth looks like a son of the gods. He calls them out. Not a hair singed, nor the smell of fire upon them. God's presence with his people is most manifest in the fire of trial." },
            { verseStart: 28, verseEnd: 30, text: "Verses 28–30 Nebuchadnezzar blesses the God of Shadrach, Meshach, and Abednego and makes a decree that no one shall speak against their God, for no other god can deliver like this. The three are promoted. Faithful witness under persecution leads to God's vindication and the advancement of his cause." },
        ],
        4: [
            { verseStart: 1, verseEnd: 9, text: "Verses 1–9 Nebuchadnezzar testifies to all nations about the signs and wonders of the Most High God. He was at ease in his palace when he had a terrifying dream. None of the wise men could interpret it. At last Daniel came, in whom is the spirit of the holy gods. He saw a great tree reaching to heaven, visible to all the earth, providing food and shelter for all creatures." },
            { verseStart: 10, verseEnd: 18, text: "Verses 10–18 A holy watcher came down from heaven crying: 'Chop down the tree! Strip its leaves, scatter its fruit. But leave the stump bound with iron and bronze in the grass. Let him be wet with the dew of heaven, and let his portion be with the beasts. Let his mind be changed from a man's, and let seven periods of time pass over him.' This decree is to teach that the Most High rules the kingdom of men and gives it to whom he will." },
            { verseStart: 19, verseEnd: 27, text: "Verses 19–27 Daniel is alarmed. The tree is Nebuchadnezzar himself — great and mighty, dominion reaching to earth's end. He will be driven from among men to live with beasts, eating grass like an ox, until seven times pass and he acknowledges that the Most High rules. Daniel counsels: 'Break off your sins by practising righteousness, and your iniquities by showing mercy to the oppressed.' Even to a pagan king, the prophet offers the way of repentance." },
            { verseStart: 28, verseEnd: 37, text: "Verses 28–37 Twelve months later, as the king boasts of his great Babylon, a voice falls from heaven: the kingdom has departed. Nebuchadnezzar is driven from men, eats grass, his body wet with dew, his hair and nails growing long. At the end of the days, he lifts his eyes to heaven, his reason returns, and he praises the Most High, whose dominion is everlasting. 'Those who walk in pride he is able to humble.' The king's testimony is a warning to all who exalt themselves." },
        ],
        5: [
            { verseStart: 1, verseEnd: 9, text: "Verses 1–9 Belshazzar the king makes a great feast for a thousand lords. Drinking wine, he commands the gold and silver vessels from the temple to be brought. They drink from them and praise the gods of gold, silver, bronze, iron, wood, and stone. Immediately, fingers of a human hand appear and write on the wall. The king's face turns pale, his knees knock. None of his wise men can read the writing." },
            { verseStart: 10, verseEnd: 17, text: "Verses 10–17 The queen remembers Daniel and his extraordinary spirit. Daniel is brought in. The king offers him gifts and the third place in the kingdom. Daniel declines the gifts but agrees to read the writing. God's servants do not serve for reward but out of faithfulness to truth." },
            { verseStart: 18, verseEnd: 28, text: "Verses 18–28 Daniel reminds Belshazzar how God humbled Nebuchadnezzar. 'You his son have not humbled your heart, though you knew all this.' The writing: MENE, MENE, TEKEL, UPHARSIN — God has numbered your kingdom and finished it; you have been weighed in the balances and found wanting; your kingdom is divided and given to the Medes and Persians. That very night Belshazzar is slain, and Darius the Mede receives the kingdom." },
            { verseStart: 29, verseEnd: 31, text: "Verses 29–31 Belshazzar commands Daniel to be clothed in purple and made third ruler. That very night Belshazzar is killed and Darius the Mede receives the kingdom, being about sixty-two years old. The swiftness of God's judgment upon proud and sacrilegious rulers is a warning to all ages." },
        ],
        6: [
            { verseStart: 1, verseEnd: 9, text: "Verses 1–9 Darius sets 120 satraps over the kingdom and three high officials, of whom Daniel was one. Daniel is distinguished above all because of his excellent spirit. His rivals seek to find grounds for complaint but cannot. They conspire to establish a decree: whoever prays to any god or man except the king for thirty days shall be cast into the den of lions. The king signs the unchangeable decree." },
            { verseStart: 10, verseEnd: 17, text: "Verses 10–17 Daniel, knowing the decree, goes home, opens his windows toward Jerusalem, and prays three times a day as he has always done. His enemies find him praying and report to the king. Darius is distressed but bound by his own law. Daniel is cast into the den of lions. The king says: 'May your God, whom you serve continually, deliver you!' A stone seals the den. Consistent prayer life is the mark of true faith — it does not alter for threats or convenience." },
            { verseStart: 18, verseEnd: 24, text: "Verses 18–24 The king fasts all night without sleep. At dawn he hurries to the den and cries: 'Daniel, servant of the living God, has your God been able to deliver you?' Daniel replies: 'My God sent his angel and shut the lions' mouths. I was found blameless before him.' Daniel is lifted out without any injury. Those who accused him are thrown in and torn apart before they reach the bottom. God vindicates the faithful and judges the accusers." },
            { verseStart: 25, verseEnd: 28, text: "Verses 25–28 Darius writes to all peoples: 'I make a decree that in all my dominion people must tremble and fear before the God of Daniel. For he is the living God, enduring forever; his kingdom shall never be destroyed. He delivers and rescues; he works signs and wonders in heaven and on earth.' Daniel prospers in the reign of Darius and Cyrus. Pagan rulers thus confess God's sovereignty repeatedly through Daniel's witness." },
        ],
        7: [
            { verseStart: 1, verseEnd: 8, text: "Verses 1–8 Daniel sees four great beasts from the sea: a lion with eagle's wings, a bear raised on one side with three ribs in its mouth, a leopard with four wings and four heads, and a fourth beast dreadful and terrible with iron teeth and ten horns. Among the horns a little horn arises, speaking great things. These represent successive world empires: Babylon, Medo-Persia, Greece, and Rome." },
            { verseStart: 9, verseEnd: 14, text: "Verses 9–14 Daniel sees thrones placed and the Ancient of Days seated — garment white as snow, hair like pure wool, throne ablaze with flames. Thousands upon thousands minister to him. The court sits in judgment and the books are opened. The little horn's beast is slain. One like a Son of Man comes with the clouds of heaven to the Ancient of Days. To him is given dominion, glory, and a kingdom — all peoples shall serve him. His dominion is everlasting. This is the supreme vision of Christ's exaltation." },
            { verseStart: 15, verseEnd: 22, text: "Verses 15–22 Daniel is grieved and troubled. An attendant explains: the four beasts are four kings. But the saints of the Most High shall receive the kingdom and possess it forever. The fourth beast shall devour the whole earth. The ten horns are ten kings; another shall arise after them, speak against the Most High, and wear out the saints. But the court shall sit and his dominion shall be taken away." },
            { verseStart: 23, verseEnd: 28, text: "Verses 23–28 The interpreting angel continues: the fourth kingdom shall be different from all others. The little horn shall speak against the Most High and think to change times and laws. The saints shall be given into his hand for a time, times, and half a time. But the court shall sit, and his dominion shall be consumed and destroyed. The kingdom under heaven shall be given to the saints of the Most High — an everlasting kingdom. Daniel keeps the matter in his heart." },
        ],
        8: [
            { verseStart: 1, verseEnd: 8, text: "Verses 1–8 In a vision Daniel sees a ram with two horns (Medo-Persia) pushing westward, northward, and southward. A male goat (Greece) comes from the west with a notable horn (Alexander). The goat strikes the ram and breaks its horns. The great horn is broken and four notable ones arise in its place — the four divisions of Alexander's empire." },
            { verseStart: 9, verseEnd: 14, text: "Verses 9–14 From one of the four horns comes a little horn (Antiochus Epiphanes), which grows exceedingly great toward the south, east, and the Beautiful Land. It becomes great, even against the host of heaven, casts down stars, and takes away the daily sacrifice. Daniel hears a holy one ask: 'How long?' — two thousand three hundred evenings and mornings, then the sanctuary shall be restored." },
            { verseStart: 15, verseEnd: 22, text: "Verses 15–22 Gabriel is sent to explain the vision. The ram is the kings of Media and Persia. The goat is Greece, the great horn its first king. The four horns represent four kingdoms from that nation, but not with its power. This vision precisely foretells the Greek conquest and its division — history confirms every detail." },
            { verseStart: 23, verseEnd: 27, text: "Verses 23–27 In the latter time, a king of fierce face, understanding dark sentences, shall arise. He shall destroy mighty and holy people, prosper by craft, and stand up against the Prince of princes. But he shall be broken without human hand. The vision is true — seal it up for many days. Daniel was appalled and sick for days. He rose and went about the king's business. Some prophecies bring distress even to the faithful who receive them." },
        ],
        9: [
            { verseStart: 1, verseEnd: 3, text: "Verses 1–3 In the first year of Darius, Daniel understands from Jeremiah's prophecy that seventy years of desolations are appointed for Jerusalem. He turns to the Lord God with prayer, fasting, sackcloth, and ashes. Scripture study leads to prayer — when Daniel reads the promise, he intercedes for its fulfilment." },
            { verseStart: 4, verseEnd: 19, text: "Verses 4–19 Daniel's prayer is a model of confession and intercession. He confesses: 'We have sinned, done wickedly, rebelled, departed from your commandments. Righteousness belongs to you, O Lord, but open shame to us.' He pleads God's mercy: 'O Lord, hear! O Lord, forgive! O Lord, pay attention and act! Delay not, for your city and your people are called by your name.' This is one of the most powerful intercessory prayers in Scripture." },
            { verseStart: 20, verseEnd: 27, text: "Verses 20–27 While Daniel is praying, Gabriel comes swiftly and gives him understanding. Seventy weeks are decreed for his people and holy city — to finish transgression, put an end to sin, atone for iniquity, bring in everlasting righteousness, seal vision and prophecy, and anoint a most holy place. From the decree to restore Jerusalem to the Anointed One shall be seven weeks and sixty-two weeks. After sixty-two weeks, the Anointed shall be cut off. This prophecy of the seventy weeks is one of the most precise Messianic predictions in the Old Testament." },
        ],
        10: [
            { verseStart: 1, verseEnd: 9, text: "Verses 1–9 In the third year of Cyrus, a revelation is given to Daniel. He mourns and fasts for three weeks. By the Tigris river, he sees a man clothed in linen with a face like lightning, eyes like flaming torches, arms and legs like burnished bronze, and a voice like the sound of a multitude. Daniel alone sees the vision; his companions flee in terror. He falls on his face in deep sleep." },
            { verseStart: 10, verseEnd: 15, text: "Verses 10–15 A hand touches Daniel and sets him trembling. The angel says: 'Fear not, Daniel, for from the first day you set your heart to understand and humbled yourself before God, your words have been heard. I have come because of your words.' The prince of the kingdom of Persia withstood the angel for twenty-one days until Michael came to help. Prayer is heard from the first day, even when the answer is delayed by spiritual warfare." },
            { verseStart: 16, verseEnd: 21, text: "Verses 16–21 One having the likeness of the children of men touches Daniel's lips. Daniel says: 'My lord, by reason of the vision pains have come upon me, and I have retained no strength.' The angel strengthens him: 'Be strong! Be strong!' Then he tells Daniel what is inscribed in the book of truth. No one contends by the angel's side except Michael, the prince of Israel. Angelic warfare and heavenly realities are as real as the earthly scenes they affect." },
        ],
        11: [
            { verseStart: 1, verseEnd: 4, text: "Verses 1–4 The angel reveals future history: three more kings shall arise in Persia, and a fourth shall stir up all against Greece. Then a mighty king shall arise (Alexander), whose kingdom shall be broken and divided toward the four winds of heaven — not to his posterity, nor with the strength he had. The precision of this prophecy matches history exactly." },
            { verseStart: 5, verseEnd: 20, text: "Verses 5–20 A detailed prophecy of the conflicts between the kings of the South (Ptolemies of Egypt) and the kings of the North (Seleucids of Syria), with Israel caught between them. Alliances, betrayals, marriage treaties, and wars are foretold with remarkable specificity. Yet through all these upheavals, God's purposes for his people stand firm." },
            { verseStart: 21, verseEnd: 35, text: "Verses 21–35 A contemptible person shall arise — not given royal majesty — who shall seize the kingdom by flattery and intrigue (Antiochus Epiphanes). He shall defile the sanctuary, take away the daily sacrifice, and set up the abomination of desolation. Those who know their God shall stand firm and take action. The wise among the people shall make many understand, though they shall fall by sword, flame, captivity, and plunder. These things purify, refine, and make the people white until the time of the end." },
            { verseStart: 36, verseEnd: 45, text: "Verses 36–45 The king shall exalt himself above every god. He shall prosper until the indignation is accomplished, for what is decreed shall be done. He shall have no regard for the gods of his fathers or for any god. At the time of the end, the king of the South and North shall clash. He shall enter the Beautiful Land, and many countries shall fall. But reports from the east and north shall alarm him, and he shall go out in great fury to destroy. He shall pitch his palatial tents between the sea and the holy mountain; yet he shall come to his end, with none to help him." },
        ],
        12: [
            { verseStart: 1, verseEnd: 4, text: "Verses 1–4 At that time Michael shall arise, the great prince who protects your people. There shall be a time of trouble such as never has been. But your people shall be delivered — everyone whose name is found written in the book. Many who sleep in the dust of the earth shall awake — some to everlasting life, and some to shame and everlasting contempt. Those who are wise shall shine like the brightness of the heavens, and those who turn many to righteousness, like the stars forever. Daniel, shut up the words and seal the book until the time of the end." },
            { verseStart: 5, verseEnd: 9, text: "Verses 5–9 Daniel sees two others standing on either side of the river. One asks the man clothed in linen: 'How long until the end of these wonders?' The answer: 'A time, times, and half a time.' When the shattering of the holy people's power is complete, all these things shall be finished. Daniel does not understand and asks for more, but is told: 'Go your way, Daniel, for the words are shut up and sealed until the time of the end.'" },
            { verseStart: 10, verseEnd: 13, text: "Verses 10–13 Many shall purify themselves, make themselves white, and be refined. The wicked shall act wickedly and none of them shall understand, but the wise shall understand. Blessed is he who waits and arrives at the end of the 1,335 days. 'But go your way till the end. You shall rest and shall stand in your allotted place at the end of the days.' Daniel's personal destiny is assured — rest now, resurrection later. This promise sustains every believer who serves faithfully until the end." },
        ],
    }
});

console.log("\n=== BATCH 2 COMPLETE (Ecclesiastes, Hosea, Daniel) ===");
const total = db.prepare(`SELECT COUNT(*) as cnt FROM commentaries`).get() as { cnt: number };
console.log(`Total commentaries: ${total.cnt}`);
db.close();
